from dataclasses import dataclass


@dataclass(frozen=True)
class MetricMethodology:
    metric_code: str
    display_name: str
    formula: str
    required_facts: tuple[str, ...]
    required_statement_sources: dict[str, tuple[str, ...]]
    period_requirements: str
    denominator_rules: str
    missing_input_behavior: str
    quality_rules: str
    methodology_notes: tuple[str, ...]
    market_inputs_required: bool = False
    support_class: str = "core_statement_based"


PROFIT_OR_LOSS = ("profit_or_loss", "segment_note", "validated_segment_reconciliation")
BALANCE_SHEET = ("financial_position", "balance_sheet", "validated_balance_sheet_reconciliation")
CASH_FLOW = ("cash_flow", "cash_flow_note")
DEBT_SOURCE = ("financial_position", "debt_note", "financial_risk_note")
MARKET_SOURCE = ("market_data",)


METHODOLOGIES: dict[str, MetricMethodology] = {
    "revenue_growth": MetricMethodology(
        "revenue_growth",
        "Revenue growth",
        "(revenue - previous_revenue) / previous_revenue",
        ("revenue", "previous_revenue"),
        {"revenue": PROFIT_OR_LOSS},
        "Comparable revenue periods only; YTD is not standalone quarter.",
        "Previous revenue denominator must be non-zero.",
        "Return missing with previous_revenue warning when prior comparable period is absent.",
        "Valid only when revenue facts are canonical, traceable, non-fixture, and period-compatible.",
        ("Do not compare standalone quarter with YTD/FY revenue.",),
        support_class="methodology_sensitive",
    ),
    "ebitda_margin": MetricMethodology(
        "ebitda_margin",
        "EBITDA margin",
        "ebitda / revenue",
        ("ebitda", "revenue"),
        {"ebitda": PROFIT_OR_LOSS, "revenue": PROFIT_OR_LOSS},
        "EBITDA and revenue must have identical coverage.",
        "Revenue denominator must be non-zero.",
        "Return missing until EBITDA is explicitly disclosed.",
        "EBITDA cannot be proxied without approved policy.",
        ("EBITDA is non-IFRS/APM; use only explicit issuer disclosure.",),
        support_class="explicit_disclosure_required",
    ),
    "operating_margin": MetricMethodology(
        "operating_margin",
        "Operating margin",
        "operating_profit / revenue",
        ("operating_profit", "revenue"),
        {"operating_profit": PROFIT_OR_LOSS, "revenue": PROFIT_OR_LOSS},
        "Operating profit and revenue must have identical YTD/FY coverage.",
        "Revenue denominator must be non-zero.",
        "Return missing with explicit missing input list.",
        "Valid when inputs are canonical exact/derived and traceable.",
        (),
    ),
    "net_margin": MetricMethodology(
        "net_margin",
        "Net margin",
        "net_income / revenue",
        ("net_income", "revenue"),
        {"net_income": PROFIT_OR_LOSS, "revenue": PROFIT_OR_LOSS},
        "Net income and revenue must have identical YTD/FY coverage.",
        "Revenue denominator must be non-zero.",
        "Return missing with explicit missing input list.",
        "Valid when inputs are canonical exact/derived and traceable.",
        (),
    ),
    "roe": MetricMethodology(
        "roe",
        "ROE",
        "net_income_ttm / average_equity",
        ("net_income", "total_equity"),
        {"net_income": PROFIT_OR_LOSS, "total_equity": BALANCE_SHEET},
        "Prefer TTM income and average equity. Ending equity fallback is derived/questionable.",
        "Average equity denominator must be non-zero.",
        "Return missing if compatible TTM income is unavailable.",
        "Questionable when average balance sheet base is unavailable.",
        ("Do not present as exact without average equity policy.",),
        support_class="methodology_sensitive",
    ),
    "roa": MetricMethodology(
        "roa",
        "ROA",
        "net_income_ttm / average_assets",
        ("net_income", "total_assets"),
        {"net_income": PROFIT_OR_LOSS, "total_assets": BALANCE_SHEET},
        "Prefer TTM income and average assets. Ending assets fallback is derived/questionable.",
        "Average assets denominator must be non-zero.",
        "Return missing if compatible TTM income is unavailable.",
        "Questionable when average balance sheet base is unavailable.",
        ("Do not present as exact without average assets policy.",),
        support_class="methodology_sensitive",
    ),
    "debt_to_equity": MetricMethodology(
        "debt_to_equity",
        "Debt to equity",
        "total_debt / total_equity",
        ("total_debt", "total_equity"),
        {"total_debt": DEBT_SOURCE, "total_equity": BALANCE_SHEET},
        "Debt and equity must be same balance sheet snapshot.",
        "Total equity denominator must be non-zero.",
        "Return missing if debt or equity is absent.",
        "Derived total_debt is allowed only via approved derived_fact_rules.",
        ("Total debt derivation must avoid current portion double-counting.",),
    ),
    "net_debt_to_ebitda": MetricMethodology(
        "net_debt_to_ebitda",
        "Net debt to EBITDA",
        "(total_debt - cash_and_equivalents) / ebitda_ttm",
        ("total_debt", "cash_and_equivalents", "ebitda"),
        {"total_debt": DEBT_SOURCE, "cash_and_equivalents": BALANCE_SHEET, "ebitda": PROFIT_OR_LOSS},
        "Net debt snapshot must be paired with compatible EBITDA TTM/FY.",
        "EBITDA denominator must be non-zero.",
        "Return missing until explicit EBITDA and compatible net debt are available.",
        "EBITDA must be explicit; total debt must be canonical/derived under approved rules.",
        ("Do not derive EBITDA from operating profit without policy.",),
        support_class="explicit_disclosure_required",
    ),
    "current_ratio": MetricMethodology(
        "current_ratio",
        "Current ratio",
        "current_assets / current_liabilities",
        ("current_assets", "current_liabilities"),
        {"current_assets": BALANCE_SHEET, "current_liabilities": BALANCE_SHEET},
        "Both inputs must be same balance sheet snapshot.",
        "Current liabilities denominator must be non-zero.",
        "Return missing if either snapshot input is absent.",
        "Valid only from canonical balance sheet current assets/current liabilities.",
        (),
    ),
    "fcf": MetricMethodology(
        "fcf",
        "Free cash flow",
        "operating_cash_flow - capex",
        ("operating_cash_flow", "capex"),
        {"operating_cash_flow": CASH_FLOW, "capex": CASH_FLOW + ("segment_note",)},
        "OCF and capex must have identical YTD/FY coverage.",
        "No denominator.",
        "Return missing if OCF or capex is absent.",
        "Segment capex is allowed only with methodology warning.",
        ("If segment capex is used, preserve warning that it is not cash-flow purchase of PPE.",),
    ),
    "fcf_margin": MetricMethodology(
        "fcf_margin",
        "FCF margin",
        "(operating_cash_flow - capex) / revenue",
        ("operating_cash_flow", "capex", "revenue"),
        {"operating_cash_flow": CASH_FLOW, "capex": CASH_FLOW + ("segment_note",), "revenue": PROFIT_OR_LOSS},
        "OCF, capex, and revenue must have identical YTD/FY coverage.",
        "Revenue denominator must be non-zero.",
        "Return missing if any input is absent.",
        "Segment capex is allowed only with methodology warning.",
        ("If segment capex is used, preserve warning that it is not cash-flow purchase of PPE.",),
    ),
    "pe_ratio": MetricMethodology(
        "pe_ratio",
        "P/E",
        "market_cap / net_income_ttm",
        ("market_cap", "net_income"),
        {"market_cap": MARKET_SOURCE, "net_income": PROFIT_OR_LOSS},
        "Requires market cap and TTM/FY net income.",
        "Net income denominator must be non-zero.",
        "Return missing without market cap / shares outstanding.",
        "Cannot be calculated from financial statements alone.",
        ("Valuation metric; not statement-only.",),
        market_inputs_required=True,
        support_class="market_valuation_required",
    ),
    "ev_to_ebitda": MetricMethodology(
        "ev_to_ebitda",
        "EV/EBITDA",
        "enterprise_value / ebitda_ttm",
        ("enterprise_value", "ebitda"),
        {"enterprise_value": MARKET_SOURCE, "ebitda": PROFIT_OR_LOSS},
        "Requires EV and explicit EBITDA TTM/FY.",
        "EBITDA denominator must be non-zero.",
        "Return missing without EV or explicit EBITDA.",
        "Cannot be calculated from statements alone when EV is absent.",
        ("Valuation metric; EBITDA must be explicit.",),
        market_inputs_required=True,
        support_class="market_valuation_required",
    ),
    "dividend_yield": MetricMethodology(
        "dividend_yield",
        "Dividend yield",
        "dividend_per_share / price",
        ("dividend_per_share", "price"),
        {"dividend_per_share": ("dividend_source",), "price": MARKET_SOURCE},
        "Requires dividend and price inputs for same security/period policy.",
        "Price denominator must be non-zero.",
        "Return missing without dividend and price data.",
        "Cannot be calculated from financial statements alone unless dividend data is separately sourced.",
        ("Valuation/income metric; not statement-only.",),
        market_inputs_required=True,
        support_class="market_valuation_required",
    ),
    "net_interest_margin": MetricMethodology(
        "net_interest_margin",
        "Net interest margin",
        "net_interest_income / average_interest_earning_assets",
        ("net_interest_income", "average_interest_earning_assets"),
        {"net_interest_income": PROFIT_OR_LOSS, "average_interest_earning_assets": BALANCE_SHEET},
        "Bank-only metric; requires explicit or approved average interest earning assets.",
        "Average interest earning assets denominator must be non-zero.",
        "Return missing until average base is available.",
        "Do not proxy average interest earning assets from total assets without policy.",
        ("Banking-sector metric; unavailable for non-bank issuers.",),
        support_class="bank_statement_based",
    ),
    "cost_to_income": MetricMethodology(
        "cost_to_income",
        "Cost to income",
        "operating_expenses / operating_income",
        ("operating_expenses", "operating_income"),
        {"operating_expenses": PROFIT_OR_LOSS, "operating_income": PROFIT_OR_LOSS},
        "Bank-only metric; operating income and expenses must cover the same period.",
        "Operating income denominator must be non-zero.",
        "Return missing with explicit missing inputs.",
        "Operating expenses may be disclosed as negative; use absolute cost magnitude.",
        ("Banking-sector metric; unavailable for non-bank issuers.",),
        support_class="bank_statement_based",
    ),
    "loan_to_deposit": MetricMethodology(
        "loan_to_deposit",
        "Loan to deposit",
        "loans_to_customers / customer_accounts",
        ("loans_to_customers", "customer_accounts"),
        {"loans_to_customers": BALANCE_SHEET, "customer_accounts": BALANCE_SHEET},
        "Bank-only metric; both inputs must be the same balance sheet snapshot.",
        "Customer accounts denominator must be non-zero.",
        "Return missing with explicit missing inputs.",
        "Do not substitute total liabilities for customer deposits.",
        ("Banking-sector metric; unavailable for non-bank issuers.",),
        support_class="bank_statement_based",
    ),
    "equity_to_assets": MetricMethodology(
        "equity_to_assets",
        "Equity to assets",
        "total_equity / total_assets",
        ("total_equity", "total_assets"),
        {"total_equity": BALANCE_SHEET, "total_assets": BALANCE_SHEET},
        "Bank-only metric; both inputs must be the same balance sheet snapshot.",
        "Total assets denominator must be non-zero.",
        "Return missing with explicit missing inputs.",
        "Use only canonical balance sheet totals.",
        ("Banking-sector metric; unavailable for non-bank issuers.",),
        support_class="bank_statement_based",
    ),
    "net_margin_like": MetricMethodology(
        "net_margin_like",
        "Net income to operating income",
        "net_income / operating_income",
        ("net_income", "operating_income"),
        {"net_income": PROFIT_OR_LOSS, "operating_income": PROFIT_OR_LOSS},
        "Bank-only profitability ratio; not the same as industrial net margin.",
        "Operating income denominator must be non-zero.",
        "Return missing with explicit missing inputs.",
        "Do not call this revenue margin.",
        ("Banking-sector metric; use cautious label to avoid confusing it with industrial net margin.",),
        support_class="bank_statement_based",
    ),
}


def get_methodology(metric_code: str) -> MetricMethodology:
    return METHODOLOGIES[metric_code]
